services:
  - type: web
    name: stock-management-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install --no-audit --no-fund --legacy-peer-deps
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: CLIENT_URL
        value: https://stock-management-rosy.vercel.app
      - key: NPM_CONFIG_AUDIT
        value: "false"
      - key: NPM_CONFIG_FUND
        value: "false"
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: "true"

